# Generated by Django 2.2.7 on 2019-12-10 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commentsmodel',
            name='surname',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
