# Generated by Django 2.2.5 on 2019-12-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_remove_clientmodel_points'),
        ('comments_app', '0002_auto_20191210_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='personal.ClientModel'),
            preserve_default=False,
        ),
    ]
