# Generated by Django 2.2.5 on 2019-12-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
