# Generated by Django 2.2.5 on 2019-12-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_breedmodel_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaclientmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.ClientModel'),
        ),
    ]
