# Generated by Django 2.2.5 on 2019-12-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20191221_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='points',
        ),
    ]
