# Generated by Django 2.2.5 on 2019-12-18 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_auto_20191219_0055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimaClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=256)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.AnimaClientModel')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.DistrictModel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.StaffModel')),
            ],
        ),
        migrations.CreateModel(
            name='BreedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='IllnessClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='VisitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=2056)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.AppointmentModel')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.IllnessClass')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.AppointmentModel')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.IllnessModel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.StatusModel')),
            ],
        ),
        migrations.AddField(
            model_name='animaclientmodel',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.AnimalModel'),
        ),
        migrations.AddField(
            model_name='animaclientmodel',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.BreedModel'),
        ),
        migrations.AddField(
            model_name='animaclientmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
