# Generated by Django 2.2.5 on 2019-12-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0003_auto_20191221_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='datetime',
            new_name='date',
        ),
    ]
