# Generated by Django 2.2.5 on 2019-12-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0004_auto_20191221_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.AnimaClientModel'),
        ),
    ]
