# Generated by Django 2.2.5 on 2019-12-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0005_auto_20191221_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
