# Generated by Django 2.2.5 on 2019-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0006_auto_20191221_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
    ]
