# Generated by Django 2.2.5 on 2019-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0007_appointmentmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
