# Generated by Django 2.2.5 on 2019-12-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0008_auto_20191221_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
