# Generated by Django 2.2.5 on 2019-12-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0009_auto_20191221_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
