# Generated by Django 2.2.5 on 2019-12-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_remove_clientmodel_points'),
        ('veterinary', '0010_auto_20191221_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illnessmodel',
            name='illness',
        ),
        migrations.AddField(
            model_name='illnessmodel',
            name='animal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='personal.AnimalModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='illnessappointment',
            name='date_start',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
