# Generated by Django 2.2.5 on 2019-12-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0011_auto_20191221_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IllnessClass',
        ),
    ]
