# Generated by Django 2.2.5 on 2019-12-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0012_delete_illnessclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnessappointment',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
