# Generated by Django 2.2.5 on 2019-12-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0014_auto_20191222_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnessappointment',
            name='date_start',
            field=models.DateField(auto_now=True),
        ),
    ]
