# Generated by Django 2.2.5 on 2019-12-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0017_auto_20191222_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
